DimeTimetrackerInvoiceBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Default:index }
    
DimeTimetrackerInvoiceBundle_customers:
    pattern:  /invoice
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Invoice:index }
    
DimeTimetrackerInvoiceBundle_activities:
    pattern:  /invoice/activities/{customer_id}
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Invoice:activities }
    
DimeTimetrackerInvoiceBundle_invoice:
    pattern:  /invoice/invoice
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Invoice:invoice }
    
DimeTimetrackerInvoiceBundle_config:
    pattern:  /invoice/config/{customer_id}
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Invoice:config }

DimeTimetrackerInvoiceBundle_first:
    pattern:  /invoice/first
    defaults: { _controller: DimeTimetrackerInvoiceBundle:Invoice:first }
    
    