services:
        buzz_request:
          class:  Dime\InvoiceBundle\Services\AuthenticatedBuzzRequest
          arguments: [@security.context]
        buzz_response:
          class:  Buzz\Message\Response
        buzz_filecontents:
          class:  Buzz\Client\FileGetContents

